/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratamentoDeDadosRouteImport } from './routes/tratamento-de-dados'
import { Route as TransparenciaInstitucionalRouteImport } from './routes/transparencia-institucional'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiconfiRouteImport } from './routes/siconfi'
import { Route as SenadoRouteImport } from './routes/senado'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ReferenciasRouteImport } from './routes/referencias'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PncpRouteImport } from './routes/pncp'
import { Route as OrgaosRouteImport } from './routes/orgaos'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as ConveniosRouteImport } from './routes/convenios'
import { Route as ContestarRouteImport } from './routes/contestar'
import { Route as CongressoRouteImport } from './routes/congresso'
import { Route as CoberturaRouteImport } from './routes/cobertura'
import { Route as CamaraRouteImport } from './routes/camara'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as AnomaliasRouteImport } from './routes/anomalias'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutoriaisIndexRouteImport } from './routes/tutoriais.index'
import { Route as TransferenciasIndexRouteImport } from './routes/transferencias.index'
import { Route as NotasIndexRouteImport } from './routes/notas.index'
import { Route as MapasIndexRouteImport } from './routes/mapas.index'
import { Route as TutoriaisSlugRouteImport } from './routes/tutoriais.$slug'
import { Route as QualidadeIdRouteImport } from './routes/qualidade.$id'
import { Route as OrgaosCodRouteImport } from './routes/orgaos_.$cod'
import { Route as NotasSlugRouteImport } from './routes/notas.$slug'
import { Route as MapasSlugRouteImport } from './routes/mapas.$slug'
import { Route as FornecedoresCnpjRouteImport } from './routes/fornecedores.$cnpj'
import { Route as ConveniosIdRouteImport } from './routes/convenios.$id'
import { Route as ContratosIdRouteImport } from './routes/contratos.$id'
import { Route as AuthenticatedMinhasMarcacoesRouteImport } from './routes/_authenticated/minhas-marcacoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SenadoVotacoesIndexRouteImport } from './routes/senado_.votacoes.index'
import { Route as SenadoSenadoresIndexRouteImport } from './routes/senado_.senadores.index'
import { Route as SenadoMateriasIndexRouteImport } from './routes/senado_.materias.index'
import { Route as CamaraVotacoesIndexRouteImport } from './routes/camara_.votacoes.index'
import { Route as CamaraProposicoesIndexRouteImport } from './routes/camara_.proposicoes.index'
import { Route as CamaraDeputadosIndexRouteImport } from './routes/camara_.deputados.index'
import { Route as TransferenciasFinalidadeIdRouteImport } from './routes/transferencias.finalidade.$id'
import { Route as TransferenciasEspeciaisIdRouteImport } from './routes/transferencias.especiais.$id'
import { Route as SenadoVotacoesIdRouteImport } from './routes/senado_.votacoes.$id'
import { Route as SenadoSenadoresIdRouteImport } from './routes/senado_.senadores.$id'
import { Route as SenadoMateriasIdRouteImport } from './routes/senado_.materias.$id'
import { Route as CamaraVotacoesIdRouteImport } from './routes/camara_.votacoes.$id'
import { Route as CamaraProposicoesIdRouteImport } from './routes/camara_.proposicoes.$id'
import { Route as CamaraDeputadosIdRouteImport } from './routes/camara_.deputados.$id'
import { Route as AuthenticatedAdminSinaisRouteImport } from './routes/_authenticated/admin_.sinais'
import { Route as AuthenticatedAdminRoadmapRouteImport } from './routes/_authenticated/admin_.roadmap'
import { Route as AuthenticatedAdminQualidadeRouteImport } from './routes/_authenticated/admin_.qualidade'
import { Route as AuthenticatedAdminMarcacoesRouteImport } from './routes/_authenticated/admin_.marcacoes'
import { Route as AuthenticatedAdminDadosRouteImport } from './routes/_authenticated/admin_.dados'
import { Route as AuthenticatedAdminArtigosRouteImport } from './routes/_authenticated/admin_.artigos'
import { Route as AuthenticatedAdminAnalisesRouteImport } from './routes/_authenticated/admin_.analises'

const TratamentoDeDadosRoute = TratamentoDeDadosRouteImport.update({
  id: '/tratamento-de-dados',
  path: '/tratamento-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaInstitucionalRoute =
  TransparenciaInstitucionalRouteImport.update({
    id: '/transparencia-institucional',
    path: '/transparencia-institucional',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiconfiRoute = SiconfiRouteImport.update({
  id: '/siconfi',
  path: '/siconfi',
  getParentRoute: () => rootRouteImport,
} as any)
const SenadoRoute = SenadoRouteImport.update({
  id: '/senado',
  path: '/senado',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciasRoute = ReferenciasRouteImport.update({
  id: '/referencias',
  path: '/referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PncpRoute = PncpRouteImport.update({
  id: '/pncp',
  path: '/pncp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgaosRoute = OrgaosRouteImport.update({
  id: '/orgaos',
  path: '/orgaos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveniosRoute = ConveniosRouteImport.update({
  id: '/convenios',
  path: '/convenios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestarRoute = ContestarRouteImport.update({
  id: '/contestar',
  path: '/contestar',
  getParentRoute: () => rootRouteImport,
} as any)
const CongressoRoute = CongressoRouteImport.update({
  id: '/congresso',
  path: '/congresso',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturaRoute = CoberturaRouteImport.update({
  id: '/cobertura',
  path: '/cobertura',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraRoute = CamaraRouteImport.update({
  id: '/camara',
  path: '/camara',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliasRoute = AnomaliasRouteImport.update({
  id: '/anomalias',
  path: '/anomalias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoriaisIndexRoute = TutoriaisIndexRouteImport.update({
  id: '/tutoriais/',
  path: '/tutoriais/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciasIndexRoute = TransferenciasIndexRouteImport.update({
  id: '/transferencias/',
  path: '/transferencias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasIndexRoute = NotasIndexRouteImport.update({
  id: '/notas/',
  path: '/notas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasIndexRoute = MapasIndexRouteImport.update({
  id: '/mapas/',
  path: '/mapas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoriaisSlugRoute = TutoriaisSlugRouteImport.update({
  id: '/tutoriais/$slug',
  path: '/tutoriais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeIdRoute = QualidadeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QualidadeRoute,
} as any)
const OrgaosCodRoute = OrgaosCodRouteImport.update({
  id: '/orgaos_/$cod',
  path: '/orgaos/$cod',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasSlugRoute = NotasSlugRouteImport.update({
  id: '/notas/$slug',
  path: '/notas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasSlugRoute = MapasSlugRouteImport.update({
  id: '/mapas/$slug',
  path: '/mapas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresCnpjRoute = FornecedoresCnpjRouteImport.update({
  id: '/fornecedores/$cnpj',
  path: '/fornecedores/$cnpj',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveniosIdRoute = ConveniosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConveniosRoute,
} as any)
const ContratosIdRoute = ContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhasMarcacoesRoute =
  AuthenticatedMinhasMarcacoesRouteImport.update({
    id: '/minhas-marcacoes',
    path: '/minhas-marcacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SenadoVotacoesIndexRoute = SenadoVotacoesIndexRouteImport.update({
  id: '/senado_/votacoes/',
  path: '/senado/votacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SenadoSenadoresIndexRoute = SenadoSenadoresIndexRouteImport.update({
  id: '/senado_/senadores/',
  path: '/senado/senadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const SenadoMateriasIndexRoute = SenadoMateriasIndexRouteImport.update({
  id: '/senado_/materias/',
  path: '/senado/materias/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraVotacoesIndexRoute = CamaraVotacoesIndexRouteImport.update({
  id: '/camara_/votacoes/',
  path: '/camara/votacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraProposicoesIndexRoute = CamaraProposicoesIndexRouteImport.update({
  id: '/camara_/proposicoes/',
  path: '/camara/proposicoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraDeputadosIndexRoute = CamaraDeputadosIndexRouteImport.update({
  id: '/camara_/deputados/',
  path: '/camara/deputados/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciasFinalidadeIdRoute =
  TransferenciasFinalidadeIdRouteImport.update({
    id: '/transferencias/finalidade/$id',
    path: '/transferencias/finalidade/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransferenciasEspeciaisIdRoute =
  TransferenciasEspeciaisIdRouteImport.update({
    id: '/transferencias/especiais/$id',
    path: '/transferencias/especiais/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const SenadoVotacoesIdRoute = SenadoVotacoesIdRouteImport.update({
  id: '/senado_/votacoes/$id',
  path: '/senado/votacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SenadoSenadoresIdRoute = SenadoSenadoresIdRouteImport.update({
  id: '/senado_/senadores/$id',
  path: '/senado/senadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SenadoMateriasIdRoute = SenadoMateriasIdRouteImport.update({
  id: '/senado_/materias/$id',
  path: '/senado/materias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraVotacoesIdRoute = CamaraVotacoesIdRouteImport.update({
  id: '/camara_/votacoes/$id',
  path: '/camara/votacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraProposicoesIdRoute = CamaraProposicoesIdRouteImport.update({
  id: '/camara_/proposicoes/$id',
  path: '/camara/proposicoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CamaraDeputadosIdRoute = CamaraDeputadosIdRouteImport.update({
  id: '/camara_/deputados/$id',
  path: '/camara/deputados/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSinaisRoute =
  AuthenticatedAdminSinaisRouteImport.update({
    id: '/admin_/sinais',
    path: '/admin/sinais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoadmapRoute =
  AuthenticatedAdminRoadmapRouteImport.update({
    id: '/admin_/roadmap',
    path: '/admin/roadmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQualidadeRoute =
  AuthenticatedAdminQualidadeRouteImport.update({
    id: '/admin_/qualidade',
    path: '/admin/qualidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMarcacoesRoute =
  AuthenticatedAdminMarcacoesRouteImport.update({
    id: '/admin_/marcacoes',
    path: '/admin/marcacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDadosRoute = AuthenticatedAdminDadosRouteImport.update({
  id: '/admin_/dados',
  path: '/admin/dados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminArtigosRoute =
  AuthenticatedAdminArtigosRouteImport.update({
    id: '/admin_/artigos',
    path: '/admin/artigos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnalisesRoute =
  AuthenticatedAdminAnalisesRouteImport.update({
    id: '/admin_/analises',
    path: '/admin/analises',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomalias': typeof AnomaliasRoute
  '/aprender': typeof AprenderRoute
  '/buscar': typeof BuscarRoute
  '/camara': typeof CamaraRoute
  '/cobertura': typeof CoberturaRoute
  '/congresso': typeof CongressoRoute
  '/contestar': typeof ContestarRoute
  '/convenios': typeof ConveniosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/metodologia': typeof MetodologiaRoute
  '/orgaos': typeof OrgaosRoute
  '/pncp': typeof PncpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/qualidade': typeof QualidadeRouteWithChildren
  '/referencias': typeof ReferenciasRoute
  '/roadmap': typeof RoadmapRoute
  '/senado': typeof SenadoRoute
  '/siconfi': typeof SiconfiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/transparencia-institucional': typeof TransparenciaInstitucionalRoute
  '/tratamento-de-dados': typeof TratamentoDeDadosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minhas-marcacoes': typeof AuthenticatedMinhasMarcacoesRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/convenios/$id': typeof ConveniosIdRoute
  '/fornecedores/$cnpj': typeof FornecedoresCnpjRoute
  '/mapas/$slug': typeof MapasSlugRoute
  '/notas/$slug': typeof NotasSlugRoute
  '/orgaos/$cod': typeof OrgaosCodRoute
  '/qualidade/$id': typeof QualidadeIdRoute
  '/tutoriais/$slug': typeof TutoriaisSlugRoute
  '/mapas/': typeof MapasIndexRoute
  '/notas/': typeof NotasIndexRoute
  '/transferencias/': typeof TransferenciasIndexRoute
  '/tutoriais/': typeof TutoriaisIndexRoute
  '/admin/analises': typeof AuthenticatedAdminAnalisesRoute
  '/admin/artigos': typeof AuthenticatedAdminArtigosRoute
  '/admin/dados': typeof AuthenticatedAdminDadosRoute
  '/admin/marcacoes': typeof AuthenticatedAdminMarcacoesRoute
  '/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/admin/roadmap': typeof AuthenticatedAdminRoadmapRoute
  '/admin/sinais': typeof AuthenticatedAdminSinaisRoute
  '/camara/deputados/$id': typeof CamaraDeputadosIdRoute
  '/camara/proposicoes/$id': typeof CamaraProposicoesIdRoute
  '/camara/votacoes/$id': typeof CamaraVotacoesIdRoute
  '/senado/materias/$id': typeof SenadoMateriasIdRoute
  '/senado/senadores/$id': typeof SenadoSenadoresIdRoute
  '/senado/votacoes/$id': typeof SenadoVotacoesIdRoute
  '/transferencias/especiais/$id': typeof TransferenciasEspeciaisIdRoute
  '/transferencias/finalidade/$id': typeof TransferenciasFinalidadeIdRoute
  '/camara/deputados/': typeof CamaraDeputadosIndexRoute
  '/camara/proposicoes/': typeof CamaraProposicoesIndexRoute
  '/camara/votacoes/': typeof CamaraVotacoesIndexRoute
  '/senado/materias/': typeof SenadoMateriasIndexRoute
  '/senado/senadores/': typeof SenadoSenadoresIndexRoute
  '/senado/votacoes/': typeof SenadoVotacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomalias': typeof AnomaliasRoute
  '/aprender': typeof AprenderRoute
  '/buscar': typeof BuscarRoute
  '/camara': typeof CamaraRoute
  '/cobertura': typeof CoberturaRoute
  '/congresso': typeof CongressoRoute
  '/contestar': typeof ContestarRoute
  '/convenios': typeof ConveniosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/metodologia': typeof MetodologiaRoute
  '/orgaos': typeof OrgaosRoute
  '/pncp': typeof PncpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/qualidade': typeof QualidadeRouteWithChildren
  '/referencias': typeof ReferenciasRoute
  '/roadmap': typeof RoadmapRoute
  '/senado': typeof SenadoRoute
  '/siconfi': typeof SiconfiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/transparencia-institucional': typeof TransparenciaInstitucionalRoute
  '/tratamento-de-dados': typeof TratamentoDeDadosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/minhas-marcacoes': typeof AuthenticatedMinhasMarcacoesRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/convenios/$id': typeof ConveniosIdRoute
  '/fornecedores/$cnpj': typeof FornecedoresCnpjRoute
  '/mapas/$slug': typeof MapasSlugRoute
  '/notas/$slug': typeof NotasSlugRoute
  '/orgaos/$cod': typeof OrgaosCodRoute
  '/qualidade/$id': typeof QualidadeIdRoute
  '/tutoriais/$slug': typeof TutoriaisSlugRoute
  '/mapas': typeof MapasIndexRoute
  '/notas': typeof NotasIndexRoute
  '/transferencias': typeof TransferenciasIndexRoute
  '/tutoriais': typeof TutoriaisIndexRoute
  '/admin/analises': typeof AuthenticatedAdminAnalisesRoute
  '/admin/artigos': typeof AuthenticatedAdminArtigosRoute
  '/admin/dados': typeof AuthenticatedAdminDadosRoute
  '/admin/marcacoes': typeof AuthenticatedAdminMarcacoesRoute
  '/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/admin/roadmap': typeof AuthenticatedAdminRoadmapRoute
  '/admin/sinais': typeof AuthenticatedAdminSinaisRoute
  '/camara/deputados/$id': typeof CamaraDeputadosIdRoute
  '/camara/proposicoes/$id': typeof CamaraProposicoesIdRoute
  '/camara/votacoes/$id': typeof CamaraVotacoesIdRoute
  '/senado/materias/$id': typeof SenadoMateriasIdRoute
  '/senado/senadores/$id': typeof SenadoSenadoresIdRoute
  '/senado/votacoes/$id': typeof SenadoVotacoesIdRoute
  '/transferencias/especiais/$id': typeof TransferenciasEspeciaisIdRoute
  '/transferencias/finalidade/$id': typeof TransferenciasFinalidadeIdRoute
  '/camara/deputados': typeof CamaraDeputadosIndexRoute
  '/camara/proposicoes': typeof CamaraProposicoesIndexRoute
  '/camara/votacoes': typeof CamaraVotacoesIndexRoute
  '/senado/materias': typeof SenadoMateriasIndexRoute
  '/senado/senadores': typeof SenadoSenadoresIndexRoute
  '/senado/votacoes': typeof SenadoVotacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anomalias': typeof AnomaliasRoute
  '/aprender': typeof AprenderRoute
  '/buscar': typeof BuscarRoute
  '/camara': typeof CamaraRoute
  '/cobertura': typeof CoberturaRoute
  '/congresso': typeof CongressoRoute
  '/contestar': typeof ContestarRoute
  '/convenios': typeof ConveniosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/metodologia': typeof MetodologiaRoute
  '/orgaos': typeof OrgaosRoute
  '/pncp': typeof PncpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/qualidade': typeof QualidadeRouteWithChildren
  '/referencias': typeof ReferenciasRoute
  '/roadmap': typeof RoadmapRoute
  '/senado': typeof SenadoRoute
  '/siconfi': typeof SiconfiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/transparencia-institucional': typeof TransparenciaInstitucionalRoute
  '/tratamento-de-dados': typeof TratamentoDeDadosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/minhas-marcacoes': typeof AuthenticatedMinhasMarcacoesRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/convenios/$id': typeof ConveniosIdRoute
  '/fornecedores/$cnpj': typeof FornecedoresCnpjRoute
  '/mapas/$slug': typeof MapasSlugRoute
  '/notas/$slug': typeof NotasSlugRoute
  '/orgaos_/$cod': typeof OrgaosCodRoute
  '/qualidade/$id': typeof QualidadeIdRoute
  '/tutoriais/$slug': typeof TutoriaisSlugRoute
  '/mapas/': typeof MapasIndexRoute
  '/notas/': typeof NotasIndexRoute
  '/transferencias/': typeof TransferenciasIndexRoute
  '/tutoriais/': typeof TutoriaisIndexRoute
  '/_authenticated/admin_/analises': typeof AuthenticatedAdminAnalisesRoute
  '/_authenticated/admin_/artigos': typeof AuthenticatedAdminArtigosRoute
  '/_authenticated/admin_/dados': typeof AuthenticatedAdminDadosRoute
  '/_authenticated/admin_/marcacoes': typeof AuthenticatedAdminMarcacoesRoute
  '/_authenticated/admin_/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/_authenticated/admin_/roadmap': typeof AuthenticatedAdminRoadmapRoute
  '/_authenticated/admin_/sinais': typeof AuthenticatedAdminSinaisRoute
  '/camara_/deputados/$id': typeof CamaraDeputadosIdRoute
  '/camara_/proposicoes/$id': typeof CamaraProposicoesIdRoute
  '/camara_/votacoes/$id': typeof CamaraVotacoesIdRoute
  '/senado_/materias/$id': typeof SenadoMateriasIdRoute
  '/senado_/senadores/$id': typeof SenadoSenadoresIdRoute
  '/senado_/votacoes/$id': typeof SenadoVotacoesIdRoute
  '/transferencias/especiais/$id': typeof TransferenciasEspeciaisIdRoute
  '/transferencias/finalidade/$id': typeof TransferenciasFinalidadeIdRoute
  '/camara_/deputados/': typeof CamaraDeputadosIndexRoute
  '/camara_/proposicoes/': typeof CamaraProposicoesIndexRoute
  '/camara_/votacoes/': typeof CamaraVotacoesIndexRoute
  '/senado_/materias/': typeof SenadoMateriasIndexRoute
  '/senado_/senadores/': typeof SenadoSenadoresIndexRoute
  '/senado_/votacoes/': typeof SenadoVotacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomalias'
    | '/aprender'
    | '/buscar'
    | '/camara'
    | '/cobertura'
    | '/congresso'
    | '/contestar'
    | '/convenios'
    | '/explorar'
    | '/login'
    | '/metodologia'
    | '/orgaos'
    | '/pncp'
    | '/privacidade'
    | '/qualidade'
    | '/referencias'
    | '/roadmap'
    | '/senado'
    | '/siconfi'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/transparencia-institucional'
    | '/tratamento-de-dados'
    | '/admin'
    | '/minhas-marcacoes'
    | '/contratos/$id'
    | '/convenios/$id'
    | '/fornecedores/$cnpj'
    | '/mapas/$slug'
    | '/notas/$slug'
    | '/orgaos/$cod'
    | '/qualidade/$id'
    | '/tutoriais/$slug'
    | '/mapas/'
    | '/notas/'
    | '/transferencias/'
    | '/tutoriais/'
    | '/admin/analises'
    | '/admin/artigos'
    | '/admin/dados'
    | '/admin/marcacoes'
    | '/admin/qualidade'
    | '/admin/roadmap'
    | '/admin/sinais'
    | '/camara/deputados/$id'
    | '/camara/proposicoes/$id'
    | '/camara/votacoes/$id'
    | '/senado/materias/$id'
    | '/senado/senadores/$id'
    | '/senado/votacoes/$id'
    | '/transferencias/especiais/$id'
    | '/transferencias/finalidade/$id'
    | '/camara/deputados/'
    | '/camara/proposicoes/'
    | '/camara/votacoes/'
    | '/senado/materias/'
    | '/senado/senadores/'
    | '/senado/votacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomalias'
    | '/aprender'
    | '/buscar'
    | '/camara'
    | '/cobertura'
    | '/congresso'
    | '/contestar'
    | '/convenios'
    | '/explorar'
    | '/login'
    | '/metodologia'
    | '/orgaos'
    | '/pncp'
    | '/privacidade'
    | '/qualidade'
    | '/referencias'
    | '/roadmap'
    | '/senado'
    | '/siconfi'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/transparencia-institucional'
    | '/tratamento-de-dados'
    | '/admin'
    | '/minhas-marcacoes'
    | '/contratos/$id'
    | '/convenios/$id'
    | '/fornecedores/$cnpj'
    | '/mapas/$slug'
    | '/notas/$slug'
    | '/orgaos/$cod'
    | '/qualidade/$id'
    | '/tutoriais/$slug'
    | '/mapas'
    | '/notas'
    | '/transferencias'
    | '/tutoriais'
    | '/admin/analises'
    | '/admin/artigos'
    | '/admin/dados'
    | '/admin/marcacoes'
    | '/admin/qualidade'
    | '/admin/roadmap'
    | '/admin/sinais'
    | '/camara/deputados/$id'
    | '/camara/proposicoes/$id'
    | '/camara/votacoes/$id'
    | '/senado/materias/$id'
    | '/senado/senadores/$id'
    | '/senado/votacoes/$id'
    | '/transferencias/especiais/$id'
    | '/transferencias/finalidade/$id'
    | '/camara/deputados'
    | '/camara/proposicoes'
    | '/camara/votacoes'
    | '/senado/materias'
    | '/senado/senadores'
    | '/senado/votacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anomalias'
    | '/aprender'
    | '/buscar'
    | '/camara'
    | '/cobertura'
    | '/congresso'
    | '/contestar'
    | '/convenios'
    | '/explorar'
    | '/login'
    | '/metodologia'
    | '/orgaos'
    | '/pncp'
    | '/privacidade'
    | '/qualidade'
    | '/referencias'
    | '/roadmap'
    | '/senado'
    | '/siconfi'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/transparencia-institucional'
    | '/tratamento-de-dados'
    | '/_authenticated/admin'
    | '/_authenticated/minhas-marcacoes'
    | '/contratos/$id'
    | '/convenios/$id'
    | '/fornecedores/$cnpj'
    | '/mapas/$slug'
    | '/notas/$slug'
    | '/orgaos_/$cod'
    | '/qualidade/$id'
    | '/tutoriais/$slug'
    | '/mapas/'
    | '/notas/'
    | '/transferencias/'
    | '/tutoriais/'
    | '/_authenticated/admin_/analises'
    | '/_authenticated/admin_/artigos'
    | '/_authenticated/admin_/dados'
    | '/_authenticated/admin_/marcacoes'
    | '/_authenticated/admin_/qualidade'
    | '/_authenticated/admin_/roadmap'
    | '/_authenticated/admin_/sinais'
    | '/camara_/deputados/$id'
    | '/camara_/proposicoes/$id'
    | '/camara_/votacoes/$id'
    | '/senado_/materias/$id'
    | '/senado_/senadores/$id'
    | '/senado_/votacoes/$id'
    | '/transferencias/especiais/$id'
    | '/transferencias/finalidade/$id'
    | '/camara_/deputados/'
    | '/camara_/proposicoes/'
    | '/camara_/votacoes/'
    | '/senado_/materias/'
    | '/senado_/senadores/'
    | '/senado_/votacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnomaliasRoute: typeof AnomaliasRoute
  AprenderRoute: typeof AprenderRoute
  BuscarRoute: typeof BuscarRoute
  CamaraRoute: typeof CamaraRoute
  CoberturaRoute: typeof CoberturaRoute
  CongressoRoute: typeof CongressoRoute
  ContestarRoute: typeof ContestarRoute
  ConveniosRoute: typeof ConveniosRouteWithChildren
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  MetodologiaRoute: typeof MetodologiaRoute
  OrgaosRoute: typeof OrgaosRoute
  PncpRoute: typeof PncpRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QualidadeRoute: typeof QualidadeRouteWithChildren
  ReferenciasRoute: typeof ReferenciasRoute
  RoadmapRoute: typeof RoadmapRoute
  SenadoRoute: typeof SenadoRoute
  SiconfiRoute: typeof SiconfiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TransparenciaInstitucionalRoute: typeof TransparenciaInstitucionalRoute
  TratamentoDeDadosRoute: typeof TratamentoDeDadosRoute
  ContratosIdRoute: typeof ContratosIdRoute
  FornecedoresCnpjRoute: typeof FornecedoresCnpjRoute
  MapasSlugRoute: typeof MapasSlugRoute
  NotasSlugRoute: typeof NotasSlugRoute
  OrgaosCodRoute: typeof OrgaosCodRoute
  TutoriaisSlugRoute: typeof TutoriaisSlugRoute
  MapasIndexRoute: typeof MapasIndexRoute
  NotasIndexRoute: typeof NotasIndexRoute
  TransferenciasIndexRoute: typeof TransferenciasIndexRoute
  TutoriaisIndexRoute: typeof TutoriaisIndexRoute
  CamaraDeputadosIdRoute: typeof CamaraDeputadosIdRoute
  CamaraProposicoesIdRoute: typeof CamaraProposicoesIdRoute
  CamaraVotacoesIdRoute: typeof CamaraVotacoesIdRoute
  SenadoMateriasIdRoute: typeof SenadoMateriasIdRoute
  SenadoSenadoresIdRoute: typeof SenadoSenadoresIdRoute
  SenadoVotacoesIdRoute: typeof SenadoVotacoesIdRoute
  TransferenciasEspeciaisIdRoute: typeof TransferenciasEspeciaisIdRoute
  TransferenciasFinalidadeIdRoute: typeof TransferenciasFinalidadeIdRoute
  CamaraDeputadosIndexRoute: typeof CamaraDeputadosIndexRoute
  CamaraProposicoesIndexRoute: typeof CamaraProposicoesIndexRoute
  CamaraVotacoesIndexRoute: typeof CamaraVotacoesIndexRoute
  SenadoMateriasIndexRoute: typeof SenadoMateriasIndexRoute
  SenadoSenadoresIndexRoute: typeof SenadoSenadoresIndexRoute
  SenadoVotacoesIndexRoute: typeof SenadoVotacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratamento-de-dados': {
      id: '/tratamento-de-dados'
      path: '/tratamento-de-dados'
      fullPath: '/tratamento-de-dados'
      preLoaderRoute: typeof TratamentoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia-institucional': {
      id: '/transparencia-institucional'
      path: '/transparencia-institucional'
      fullPath: '/transparencia-institucional'
      preLoaderRoute: typeof TransparenciaInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siconfi': {
      id: '/siconfi'
      path: '/siconfi'
      fullPath: '/siconfi'
      preLoaderRoute: typeof SiconfiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senado': {
      id: '/senado'
      path: '/senado'
      fullPath: '/senado'
      preLoaderRoute: typeof SenadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencias': {
      id: '/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof ReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pncp': {
      id: '/pncp'
      path: '/pncp'
      fullPath: '/pncp'
      preLoaderRoute: typeof PncpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgaos': {
      id: '/orgaos'
      path: '/orgaos'
      fullPath: '/orgaos'
      preLoaderRoute: typeof OrgaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convenios': {
      id: '/convenios'
      path: '/convenios'
      fullPath: '/convenios'
      preLoaderRoute: typeof ConveniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestar': {
      id: '/contestar'
      path: '/contestar'
      fullPath: '/contestar'
      preLoaderRoute: typeof ContestarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congresso': {
      id: '/congresso'
      path: '/congresso'
      fullPath: '/congresso'
      preLoaderRoute: typeof CongressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobertura': {
      id: '/cobertura'
      path: '/cobertura'
      fullPath: '/cobertura'
      preLoaderRoute: typeof CoberturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara': {
      id: '/camara'
      path: '/camara'
      fullPath: '/camara'
      preLoaderRoute: typeof CamaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalias': {
      id: '/anomalias'
      path: '/anomalias'
      fullPath: '/anomalias'
      preLoaderRoute: typeof AnomaliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoriais/': {
      id: '/tutoriais/'
      path: '/tutoriais'
      fullPath: '/tutoriais/'
      preLoaderRoute: typeof TutoriaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencias/': {
      id: '/transferencias/'
      path: '/transferencias'
      fullPath: '/transferencias/'
      preLoaderRoute: typeof TransferenciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas/': {
      id: '/notas/'
      path: '/notas'
      fullPath: '/notas/'
      preLoaderRoute: typeof NotasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas/': {
      id: '/mapas/'
      path: '/mapas'
      fullPath: '/mapas/'
      preLoaderRoute: typeof MapasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutoriais/$slug': {
      id: '/tutoriais/$slug'
      path: '/tutoriais/$slug'
      fullPath: '/tutoriais/$slug'
      preLoaderRoute: typeof TutoriaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade/$id': {
      id: '/qualidade/$id'
      path: '/$id'
      fullPath: '/qualidade/$id'
      preLoaderRoute: typeof QualidadeIdRouteImport
      parentRoute: typeof QualidadeRoute
    }
    '/orgaos_/$cod': {
      id: '/orgaos_/$cod'
      path: '/orgaos/$cod'
      fullPath: '/orgaos/$cod'
      preLoaderRoute: typeof OrgaosCodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas/$slug': {
      id: '/notas/$slug'
      path: '/notas/$slug'
      fullPath: '/notas/$slug'
      preLoaderRoute: typeof NotasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas/$slug': {
      id: '/mapas/$slug'
      path: '/mapas/$slug'
      fullPath: '/mapas/$slug'
      preLoaderRoute: typeof MapasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/$cnpj': {
      id: '/fornecedores/$cnpj'
      path: '/fornecedores/$cnpj'
      fullPath: '/fornecedores/$cnpj'
      preLoaderRoute: typeof FornecedoresCnpjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convenios/$id': {
      id: '/convenios/$id'
      path: '/$id'
      fullPath: '/convenios/$id'
      preLoaderRoute: typeof ConveniosIdRouteImport
      parentRoute: typeof ConveniosRoute
    }
    '/contratos/$id': {
      id: '/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof ContratosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minhas-marcacoes': {
      id: '/_authenticated/minhas-marcacoes'
      path: '/minhas-marcacoes'
      fullPath: '/minhas-marcacoes'
      preLoaderRoute: typeof AuthenticatedMinhasMarcacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/senado_/votacoes/': {
      id: '/senado_/votacoes/'
      path: '/senado/votacoes'
      fullPath: '/senado/votacoes/'
      preLoaderRoute: typeof SenadoVotacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senado_/senadores/': {
      id: '/senado_/senadores/'
      path: '/senado/senadores'
      fullPath: '/senado/senadores/'
      preLoaderRoute: typeof SenadoSenadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senado_/materias/': {
      id: '/senado_/materias/'
      path: '/senado/materias'
      fullPath: '/senado/materias/'
      preLoaderRoute: typeof SenadoMateriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara_/votacoes/': {
      id: '/camara_/votacoes/'
      path: '/camara/votacoes'
      fullPath: '/camara/votacoes/'
      preLoaderRoute: typeof CamaraVotacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara_/proposicoes/': {
      id: '/camara_/proposicoes/'
      path: '/camara/proposicoes'
      fullPath: '/camara/proposicoes/'
      preLoaderRoute: typeof CamaraProposicoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara_/deputados/': {
      id: '/camara_/deputados/'
      path: '/camara/deputados'
      fullPath: '/camara/deputados/'
      preLoaderRoute: typeof CamaraDeputadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencias/finalidade/$id': {
      id: '/transferencias/finalidade/$id'
      path: '/transferencias/finalidade/$id'
      fullPath: '/transferencias/finalidade/$id'
      preLoaderRoute: typeof TransferenciasFinalidadeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencias/especiais/$id': {
      id: '/transferencias/especiais/$id'
      path: '/transferencias/especiais/$id'
      fullPath: '/transferencias/especiais/$id'
      preLoaderRoute: typeof TransferenciasEspeciaisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senado_/votacoes/$id': {
      id: '/senado_/votacoes/$id'
      path: '/senado/votacoes/$id'
      fullPath: '/senado/votacoes/$id'
      preLoaderRoute: typeof SenadoVotacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senado_/senadores/$id': {
      id: '/senado_/senadores/$id'
      path: '/senado/senadores/$id'
      fullPath: '/senado/senadores/$id'
      preLoaderRoute: typeof SenadoSenadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senado_/materias/$id': {
      id: '/senado_/materias/$id'
      path: '/senado/materias/$id'
      fullPath: '/senado/materias/$id'
      preLoaderRoute: typeof SenadoMateriasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara_/votacoes/$id': {
      id: '/camara_/votacoes/$id'
      path: '/camara/votacoes/$id'
      fullPath: '/camara/votacoes/$id'
      preLoaderRoute: typeof CamaraVotacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara_/proposicoes/$id': {
      id: '/camara_/proposicoes/$id'
      path: '/camara/proposicoes/$id'
      fullPath: '/camara/proposicoes/$id'
      preLoaderRoute: typeof CamaraProposicoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camara_/deputados/$id': {
      id: '/camara_/deputados/$id'
      path: '/camara/deputados/$id'
      fullPath: '/camara/deputados/$id'
      preLoaderRoute: typeof CamaraDeputadosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/sinais': {
      id: '/_authenticated/admin_/sinais'
      path: '/admin/sinais'
      fullPath: '/admin/sinais'
      preLoaderRoute: typeof AuthenticatedAdminSinaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/roadmap': {
      id: '/_authenticated/admin_/roadmap'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AuthenticatedAdminRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/qualidade': {
      id: '/_authenticated/admin_/qualidade'
      path: '/admin/qualidade'
      fullPath: '/admin/qualidade'
      preLoaderRoute: typeof AuthenticatedAdminQualidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/marcacoes': {
      id: '/_authenticated/admin_/marcacoes'
      path: '/admin/marcacoes'
      fullPath: '/admin/marcacoes'
      preLoaderRoute: typeof AuthenticatedAdminMarcacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/dados': {
      id: '/_authenticated/admin_/dados'
      path: '/admin/dados'
      fullPath: '/admin/dados'
      preLoaderRoute: typeof AuthenticatedAdminDadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/artigos': {
      id: '/_authenticated/admin_/artigos'
      path: '/admin/artigos'
      fullPath: '/admin/artigos'
      preLoaderRoute: typeof AuthenticatedAdminArtigosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin_/analises': {
      id: '/_authenticated/admin_/analises'
      path: '/admin/analises'
      fullPath: '/admin/analises'
      preLoaderRoute: typeof AuthenticatedAdminAnalisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMinhasMarcacoesRoute: typeof AuthenticatedMinhasMarcacoesRoute
  AuthenticatedAdminAnalisesRoute: typeof AuthenticatedAdminAnalisesRoute
  AuthenticatedAdminArtigosRoute: typeof AuthenticatedAdminArtigosRoute
  AuthenticatedAdminDadosRoute: typeof AuthenticatedAdminDadosRoute
  AuthenticatedAdminMarcacoesRoute: typeof AuthenticatedAdminMarcacoesRoute
  AuthenticatedAdminQualidadeRoute: typeof AuthenticatedAdminQualidadeRoute
  AuthenticatedAdminRoadmapRoute: typeof AuthenticatedAdminRoadmapRoute
  AuthenticatedAdminSinaisRoute: typeof AuthenticatedAdminSinaisRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMinhasMarcacoesRoute: AuthenticatedMinhasMarcacoesRoute,
  AuthenticatedAdminAnalisesRoute: AuthenticatedAdminAnalisesRoute,
  AuthenticatedAdminArtigosRoute: AuthenticatedAdminArtigosRoute,
  AuthenticatedAdminDadosRoute: AuthenticatedAdminDadosRoute,
  AuthenticatedAdminMarcacoesRoute: AuthenticatedAdminMarcacoesRoute,
  AuthenticatedAdminQualidadeRoute: AuthenticatedAdminQualidadeRoute,
  AuthenticatedAdminRoadmapRoute: AuthenticatedAdminRoadmapRoute,
  AuthenticatedAdminSinaisRoute: AuthenticatedAdminSinaisRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ConveniosRouteChildren {
  ConveniosIdRoute: typeof ConveniosIdRoute
}

const ConveniosRouteChildren: ConveniosRouteChildren = {
  ConveniosIdRoute: ConveniosIdRoute,
}

const ConveniosRouteWithChildren = ConveniosRoute._addFileChildren(
  ConveniosRouteChildren,
)

interface QualidadeRouteChildren {
  QualidadeIdRoute: typeof QualidadeIdRoute
}

const QualidadeRouteChildren: QualidadeRouteChildren = {
  QualidadeIdRoute: QualidadeIdRoute,
}

const QualidadeRouteWithChildren = QualidadeRoute._addFileChildren(
  QualidadeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnomaliasRoute: AnomaliasRoute,
  AprenderRoute: AprenderRoute,
  BuscarRoute: BuscarRoute,
  CamaraRoute: CamaraRoute,
  CoberturaRoute: CoberturaRoute,
  CongressoRoute: CongressoRoute,
  ContestarRoute: ContestarRoute,
  ConveniosRoute: ConveniosRouteWithChildren,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  MetodologiaRoute: MetodologiaRoute,
  OrgaosRoute: OrgaosRoute,
  PncpRoute: PncpRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QualidadeRoute: QualidadeRouteWithChildren,
  ReferenciasRoute: ReferenciasRoute,
  RoadmapRoute: RoadmapRoute,
  SenadoRoute: SenadoRoute,
  SiconfiRoute: SiconfiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TransparenciaInstitucionalRoute: TransparenciaInstitucionalRoute,
  TratamentoDeDadosRoute: TratamentoDeDadosRoute,
  ContratosIdRoute: ContratosIdRoute,
  FornecedoresCnpjRoute: FornecedoresCnpjRoute,
  MapasSlugRoute: MapasSlugRoute,
  NotasSlugRoute: NotasSlugRoute,
  OrgaosCodRoute: OrgaosCodRoute,
  TutoriaisSlugRoute: TutoriaisSlugRoute,
  MapasIndexRoute: MapasIndexRoute,
  NotasIndexRoute: NotasIndexRoute,
  TransferenciasIndexRoute: TransferenciasIndexRoute,
  TutoriaisIndexRoute: TutoriaisIndexRoute,
  CamaraDeputadosIdRoute: CamaraDeputadosIdRoute,
  CamaraProposicoesIdRoute: CamaraProposicoesIdRoute,
  CamaraVotacoesIdRoute: CamaraVotacoesIdRoute,
  SenadoMateriasIdRoute: SenadoMateriasIdRoute,
  SenadoSenadoresIdRoute: SenadoSenadoresIdRoute,
  SenadoVotacoesIdRoute: SenadoVotacoesIdRoute,
  TransferenciasEspeciaisIdRoute: TransferenciasEspeciaisIdRoute,
  TransferenciasFinalidadeIdRoute: TransferenciasFinalidadeIdRoute,
  CamaraDeputadosIndexRoute: CamaraDeputadosIndexRoute,
  CamaraProposicoesIndexRoute: CamaraProposicoesIndexRoute,
  CamaraVotacoesIndexRoute: CamaraVotacoesIndexRoute,
  SenadoMateriasIndexRoute: SenadoMateriasIndexRoute,
  SenadoSenadoresIndexRoute: SenadoSenadoresIndexRoute,
  SenadoVotacoesIndexRoute: SenadoVotacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
